spring.application.name=ApiRest

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#PROFILE DEFAULT
spring.profiles.active=dev